name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: |
        export LC_CTYPE="C.UTF-8"
    - name: Install tools
      run: |
        sudo apt update; sudo apt install -y curl python3 python3-venv
    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    - name: Fix poetry script
      run: |
        sed -i -e 's|#!/usr/bin/env python|#!/usr/bin/env python3|g' ~/.poetry/bin/poetry
    - name: Enable poetry
      run: |
        source $HOME/.poetry/env
    - name: Install dependencies modules
      run: |
        poetry install
    - name: Run pytest
      run: |
        poetry run pytest
